version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: monthly
    timezone: Europe/Paris
  open-pull-requests-limit: 20
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Paris
  open-pull-requests-limit: 20
