image:
  file: .gitpod.Dockerfile

tasks:
  - before : mysql -h localhost -u root < sql/prepare_db.sql &&
              mysql -h localhost -u root myGuild_db < sql/init_tables.sql &&
              mysql -h localhost -u root myGuild_db < sql/add_data_dev.sql
  - command : mvn -DskipTests clean package

vscode:
  extensions:
    - vscjava.vscode-java-debug@0.23.0:3ARqL3kPh1J1SwpVjYUjqw==
    - redhat.java@0.54.2:Q60n5quUtfd1EcwzkRq96A==
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
    - cool2k.vscode-lombok@1.0.2:e816/wZO588Jp8PN58Wj6g==
    - formulahendry.vscode-mysql@0.4.0:IAUm3OoC/011qAjawyOjqw==