application:
  guild:
    slug: PeyPouZe
    realm: Archimonde
  server:
    port: 2142
    url: http://localhost
  db-param:
    host: localhost
    port: 3306
    db-name: myGuild_db
    user: myGuild_user
    password: MyGuildPass2020
  blizzard:
    wow:
      delay-ms: 1
      profile:
        base-uri: https://eu.api.blizzard.com/profile
        namespace: profile-eu
      game-data:
        base-uri: https://eu.api.blizzard.com/data/wow
        namespace: static-eu

logging:
  level:
    fr.opendoha.myguild.server:
      tools:
        HttpHelper: INFO
        handler.GlobalExceptionHandler: INFO
      MyGuildApplication: INFO
      service:
        BlizzardService: INFO
        oauth2:
          BlizzardOAuth2FlowHandler: INFO
      aop.interceptor: 
        GeneralInterceptor: INFO
        ServiceInterceptor: INFO
    org:
      apache: INFO
      springframework:
        web.client.RestTemplate: INFO
        security: INFO
        data: INFO

server:
  port : ${application.server.port}

spring:
  jpa:
    show-sql: false
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  security:
    oauth2:
      client:
        registration:
          oauth-blizzard:
            client-id: 154f1ea2fa934b02a608eb6027cf527e
            client-secret: ARdKjDop8uMrjlnjzBfEOiK69lUeFB9e
            client-name: testpourmanagementdeguilde
            provider: blizzard
            scope: wow.profile
            redirect-uri: "${application.server.url}:${application.server.port}/login/oauth2/code/oauth-blizzard"
            client-authentication-method: basic
            authorization-grant-type: authorization_code 
        provider:
          blizzard:
            issuer-uri: https://eu.battle.net/oauth
            authorization-uri: https://eu.battle.net/oauth/authorize
            token-uri: https://eu.battle.net/oauth/token
            user-info-uri: https://eu.battle.net/oauth/userinfo
            user-name-attribute: battletag
  
  datasource:
    url: jdbc:mysql://${application.db-param.host}:${application.db-param.port}/${application.db-param.db-name}
    username: ${application.db-param.user}
    password: ${application.db-param.password}
    driverClassName: com.mysql.cj.jdbc.Driver