Application:
  db-param:
    host: localhost
    port: 3306
    db-name: myGuild_db
    user: myGuild_user
    password: MyGuildPass2020

logging:
  level:
    fr.jbwittner.myguild.server:
      MyGuildApplication: INFO
      aop.interceptor: 
        GeneralInterceptor: INFO
        ServiceInterceptor: INFO
    org:
      apache: INFO
      springframework:
        security: INFO
        data: INFO

server:
  port : 2142

spring:
  jpa:
    database-platform : org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  datasource:
    url: jdbc:mariadb://${application.db-param.host}:${application.db-param.port}/${application.db-param.db-name}
    databaseName: ${application.db-param.db-name}
    username: ${application.db-param.user}
    password: ${application.db-param.password}
    driverClassName: org.mariadb.jdbc.Driver