# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Project CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - develop

jobs:
  check:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup-Java
      uses: actions/setup-java@v1
      with:
        java-version: 11 # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2/repository
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Generation PMD report
      run: mvn -B pmd:pmd -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: Check PMD report
      run: mvn -B pmd:check -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    
  build:
    needs: [check]
    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup-Java
      uses: actions/setup-java@v1
      with:
        java-version: 11 # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
        
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2/repository
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build java part
      run: mvn -B compile --file pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  
  test:
    needs: [build]
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup-Java
      uses: actions/setup-java@v1
      with:
        java-version: 11 # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
        
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2/repository
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - name: Test with Maven
      run: mvn -B test --file pom.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: Coverage
      uses: codecov/codecov-action@v1
